import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Providers from './Providers'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <Providers>
                    <NavBar />
                    <main className="px-5 md:px-0 container mx-auto">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
